# Generated by Django 4.2.11 on 2025-10-06 02:29

import django.core.validators
from django.db import migrations, models
import locations.models.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Name of the city', max_length=200)),
                ('asciiname', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text="Numeric administrative code for level 3 (e.g., '4285' for Hatkanangale)", max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, help_text="Latitude of the city's central point (optional)", null=True)),
                ('longitude', models.FloatField(blank=True, help_text="Longitude of the city's central point (optional)", null=True)),
                ('location_source', models.CharField(blank=True, help_text="Source of the city data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CustomCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('asciiname', models.CharField(blank=True, max_length=100, null=True)),
                ('alternatenames', models.TextField(blank=True, help_text='Comma-separated list of alternate names', null=True)),
                ('country_code', models.CharField(blank=True, help_text='ISO-3166 2-letter country code', max_length=2, null=True)),
                ('country_capital', models.CharField(blank=True, help_text='Capital city of the country', max_length=100, null=True)),
                ('currency_symbol', models.CharField(blank=True, help_text='Currency symbol (e.g., ₹)', max_length=10, null=True)),
                ('currency_code', models.CharField(blank=True, help_text='ISO 4217 currency code (e.g., INR)', max_length=3, null=True)),
                ('currency_name', models.CharField(blank=True, help_text='Currency name (e.g., Indian Rupee)', max_length=50, null=True)),
                ('country_phone_code', models.CharField(blank=True, help_text='Country phone code (e.g., +91)', max_length=10, null=True)),
                ('postal_code_regex', models.CharField(blank=True, help_text='Regex for postal code validation', max_length=300, null=True)),
                ('country_languages', models.TextField(blank=True, help_text='Comma-separated list of language codes (e.g., hi,en)', max_length=300, null=True)),
                ('population', models.BigIntegerField(blank=True, help_text='Country population', null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('has_postal_code', models.BooleanField(default=True)),
                ('postal_code_length', models.CharField(blank=True, help_text='Maximum postal code length allowed for given country', max_length=20, null=True)),
                ('phone_number_length', models.CharField(blank=True, help_text='Maximum phone number length allowed for given country', max_length=20, null=True)),
                ('admin_codes', models.JSONField(blank=True, help_text="JSON object storing admin codes, e.g., {'admin1_codes': ['13', '14'], 'admin2_codes': ['594'], ...}", null=True)),
                ('location_source', models.CharField(blank=True, help_text="Source of the country data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='CustomRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="Name of the region (e.g., 'Kerala' for admin1_code '13')", max_length=200)),
                ('asciiname', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, help_text="Numeric administrative code for level 1 (e.g., '13' for Kerala)", max_length=20, null=True)),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('location_source', models.CharField(blank=True, help_text="Source of country's region data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Region/State',
                'verbose_name_plural': 'Regions/States',
            },
        ),
        migrations.CreateModel(
            name='CustomSubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="Name of the subregion (e.g., 'Kolhapur' for admin2_code '594')", max_length=200)),
                ('asciiname', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, help_text="Numeric administrative code for level 2 (e.g., '594' for Kolhapur)", max_length=20, null=True)),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('location_source', models.CharField(blank=True, help_text="Source of country's subregion data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Subregion/District',
                'verbose_name_plural': 'Subregions/Districts',
            },
        ),
        migrations.CreateModel(
            name='GlobalRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('asciiname', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('location_source', models.CharField(blank=True, help_text="Source of the global region data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Global Region',
                'verbose_name_plural': 'Global Regions',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, help_text="Numeric administrative code for level 4 (e.g., '1234' for a locality)", max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code (e.g., Indian PIN code for India)', max_length=20, null=True)),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the location (optional)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the location (optional)', null=True)),
                ('location_source', models.CharField(blank=True, help_text="Source of the location data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['city__name'],
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('timezone_id', models.CharField(help_text="IANA Time Zone ID (e.g., 'Asia/Kolkata')", max_length=100, primary_key=True, serialize=False, validators=[locations.models.timezone.validate_timezone_id])),
                ('gmt_offset_jan', models.DecimalField(decimal_places=1, help_text='GMT offset in January (hours, e.g., 5.5)', max_digits=4, validators=[locations.models.timezone.validate_offset])),
                ('dst_offset_jul', models.DecimalField(decimal_places=1, help_text='DST offset in July (hours, e.g., 5.5)', max_digits=4, validators=[locations.models.timezone.validate_offset])),
                ('raw_offset', models.DecimalField(decimal_places=1, help_text='Standard time offset without DST (hours, e.g., 5.5)', max_digits=4, validators=[locations.models.timezone.validate_offset])),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the timezone is currently in use')),
                ('display_name', models.CharField(help_text="Human-readable timezone name (e.g., 'India Standard Time')", max_length=150)),
                ('country_code', models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code from CustomCountry (e.g., 'IN' for India)", max_length=2, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Country code must be two uppercase letters.'), locations.models.timezone.validate_country_code])),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Timezones',
            },
        ),
    ]
