# Generated by Django 4.2.11 on 2025-06-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('industry', models.CharField(blank=True, choices=[('aerospace', 'Aerospace'), ('agriculture', 'Agriculture'), ('automotive', 'Automotive'), ('banking', 'Banking'), ('biotechnology', 'Biotechnology'), ('chemicals', 'Chemicals'), ('construction', 'Construction'), ('consumer_goods', 'Consumer Goods'), ('education', 'Education'), ('energy', 'Energy'), ('entertainment', 'Entertainment'), ('finance', 'Finance'), ('food_beverage', 'Food & Beverage'), ('healthcare', 'Healthcare'), ('hospitality', 'Hospitality'), ('information_technology', 'Information Technology'), ('insurance', 'Insurance'), ('logistics', 'Logistics'), ('manufacturing', 'Manufacturing'), ('media', 'Media'), ('mining', 'Mining'), ('pharmaceuticals', 'Pharmaceuticals'), ('real_estate', 'Real Estate'), ('retail', 'Retail'), ('telecommunications', 'Telecommunications'), ('transportation', 'Transportation'), ('utilities', 'Utilities')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companies', models.ManyToManyField(blank=True, to='clients.company')),
            ],
        ),
    ]
