# Generated by Django 4.2.11 on 2025-10-06 02:29

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text="Description of the billing schedule (e.g., 'Monthly subscription').", max_length=255)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], help_text='Frequency of billing (e.g., MONTHLY, QUARTERLY).', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Start date of the billing schedule.')),
                ('end_date', models.DateField(blank=True, help_text='End date of the billing schedule (optional).', null=True)),
                ('next_billing_date', models.DateField(help_text='Date for the next scheduled invoice.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fixed amount to be billed per cycle.', max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Status of the billing schedule (e.g., ACTIVE, PAUSED, COMPLETED).', max_length=20)),
            ],
            options={
                'verbose_name': 'Billing Schedule',
                'verbose_name_plural': 'Billing Schedules',
                'db_table': 'billing_schedule',
                'ordering': ['-start_date', 'entity'],
            },
        ),
        migrations.CreateModel(
            name='GSTConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cgst_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Central GST rate (if applicable).', max_digits=5, null=True)),
                ('sgst_rate', models.DecimalField(blank=True, decimal_places=2, help_text='State GST rate (if applicable).', max_digits=5, null=True)),
                ('igst_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Integrated GST rate (if applicable).', max_digits=5, null=True)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CGST amount', max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SGST amount', max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IGST amount', max_digits=15)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text="Description of the GST configuration (e.g., 'Standard GST for electronics').", max_length=255)),
                ('rate_type', models.CharField(choices=[('STANDARD', 'Standard'), ('EXEMPT', 'Exempt'), ('ZERO_RATED', 'Zero-Rated')], default='STANDARD', help_text='Type of GST rate (e.g., STANDARD, EXEMPT, ZERO_RATED).', max_length=20)),
                ('effective_from', models.DateField(help_text='Date from which this GST configuration is effective.')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this GST configuration is effective (optional).', null=True)),
            ],
            options={
                'verbose_name': 'GST Configuration',
                'verbose_name_plural': 'GST Configurations',
                'db_table': 'gst_configuration',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cgst_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Central GST rate (if applicable).', max_digits=5, null=True)),
                ('sgst_rate', models.DecimalField(blank=True, decimal_places=2, help_text='State GST rate (if applicable).', max_digits=5, null=True)),
                ('igst_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Integrated GST rate (if applicable).', max_digits=5, null=True)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CGST amount', max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SGST amount', max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IGST amount', max_digits=15)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Unique invoice number.', max_length=30, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description of the invoice.', max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date when the invoice was issued.', null=True)),
                ('due_date', models.DateField(help_text='Date when the invoice payment is due.')),
                ('payment_terms', models.CharField(blank=True, choices=[('NET_30', 'Net 30'), ('NET_60', 'Net 60'), ('NET_90', 'Net 90'), ('DUE_ON_RECEIPT', 'Due on Receipt')], default='NET_30', help_text='Payment terms for the invoice.', max_length=20)),
                ('currency', models.CharField(blank=True, choices=[('INR', 'INR')], default='INR', help_text='Currency of the invoice.', max_length=3)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Base amount of the invoice before taxes.', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount including taxes.', max_digits=12)),
                ('tax_exemption_status', models.CharField(blank=True, choices=[('NONE', 'None'), ('EXEMPT', 'Tax Exempt'), ('ZERO_RATED', 'Zero-Rated')], default='NONE', help_text='Tax exemption status of the invoice.', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'Unified Payments Interface'), ('CC', 'Credit Card'), ('DC', 'Debit Card'), ('NEFT', 'National Electronic Funds Transfer'), ('RTGS', 'Real Time Gross Settlement'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer'), ('WIRE_TRANSFER', 'Wire Transfer'), ('DIRECT_DEBIT', 'Direct Debit'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('DIGITAL_WALLET', 'Digital Wallet'), ('ACH', 'Automated Clearing House'), ('SEPA', 'Single Euro Payments Area'), ('MOBILE_PAYMENT', 'Mobile Payment'), ('PREPAID_CARD', 'Prepaid Card'), ('INSTANT_PAYMENT', 'Instant Payment'), ('CRYPTOCURRENCY', 'Cryptocurrency')], help_text='Payment method used (e.g., UPI, CREDIT_CARD).', max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Reference for the payment (e.g., transaction ID).', max_length=100, null=True)),
                ('issuer_gstin', models.CharField(blank=True, help_text='GSTIN of the issuer (for Indian invoices).', max_length=15, null=True)),
                ('recipient_gstin', models.CharField(blank=True, help_text='GSTIN of the recipient (for Indian invoices).', max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoice',
                'ordering': ['-issue_date', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cgst_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Central GST rate (if applicable).', max_digits=5, null=True)),
                ('sgst_rate', models.DecimalField(blank=True, decimal_places=2, help_text='State GST rate (if applicable).', max_digits=5, null=True)),
                ('igst_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Integrated GST rate (if applicable).', max_digits=5, null=True)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CGST amount', max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SGST amount', max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IGST amount', max_digits=15)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Description of the line item (e.g., product or service name).', max_length=255)),
                ('hsn_sac_code', models.CharField(blank=True, help_text='HSN or SAC code for the item (used for Indian GST compliance).', max_length=8, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of the item.', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit of the item.', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to this line item.', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for this line item after taxes and discount.', max_digits=12)),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'db_table': 'line_item',
                'ordering': ['invoice', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the payment.', max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the payment was made.')),
                ('payment_reference', models.CharField(blank=True, help_text='Reference for the payment (e.g., transaction ID).', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Status of the payment (e.g., PENDING, COMPLETED, FAILED).', max_length=20)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
                'ordering': ['-payment_date', 'invoice'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code for the payment method (e.g., UPI, CREDIT_CARD).', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name of the payment method (e.g., Unified Payments Interface).', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional description of the payment method.', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is currently available for use.')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_method',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name of the status (e.g., 'Draft').", max_length=50, unique=True)),
                ('code', models.CharField(help_text="Unique code for the status (e.g., 'DRAFT').", max_length=20, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default status for new invoices.')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether invoices with this status are locked from edits.')),
            ],
            options={
                'verbose_name': 'Invoice Status',
                'verbose_name_plural': 'Invoice Statuses',
                'db_table': 'status',
                'ordering': ['name'],
            },
        ),
    ]
